# Generated by Django 4.1.2 on 2022-11-28 20:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discussion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
