# Generated by Django 4.1.2 on 2022-12-05 19:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_discussion_author_forum_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.Discussion.image_upload_to),
        ),
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.Forum.image_upload_to),
        ),
    ]
